name: Build2
on:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  x86_64_linux:
    name: "x86_64 Linux"
    runs-on: [ubuntu-22.04]
    container: nvidia/cuda:11.7.1-devel-ubuntu22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: "Build"
      run: |
        nvcc src/main.cu -o x86_64_linux.bin -O3 -Xptxas -v -Xcompiler -static-libgcc -Xcompiler -static-libstdc++ -gencode arch=compute_52,code=compute_52

    - uses: ncipollo/release-action@v1
      with:
        artifacts: x86_64_linux.bin
        allowUpdates: true
        draft: true
        replacesArtifacts: false
